# Generated by Django 5.0.6 on 2024-06-18 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBookme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='editoriales',
            name='contacto',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
