# Generated by Django 5.0.6 on 2024-06-18 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBookme', '0002_editoriales_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editoriales',
            name='libros',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editorial', to='AppBookme.libro'),
        ),
    ]
