# Generated by Django 5.0.6 on 2024-06-19 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBookme', '0006_alter_editoriales_libros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editoriales',
            name='libros',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='editorial', to='AppBookme.libro'),
        ),
    ]
